module.exports = {
    datastore: 'sj3',
    tableName: 'vw_stok',
    migrate: 'safe',
    attributes: {
        id: { columnName: 'id', type: 'number', required: true },
        grpbrg: 'string',
        namagrp: 'string',
        stsrec: 'string',
        stok: 'number',
        stok1: 'number',
        stok2: 'number',
        stok3: 'number',
        stn1: 'string',
        stn2: 'string',
        stn3: 'string',
        sts1: 'string',
        sts2: 'string',
        sts3: 'string',
        hjual1: 'number',
        hjual2: 'number',
        hjual3: 'number',
        hbeli1: 'number',
        hbeli2: 'number',
        hbeli3: 'number',
        hpp1: 'number',
        hpp2: 'number',
        hpp3: 'number',
        nama1: 'string',
        nama2: 'string',
        nama3: 'string',
        kdbrg1: 'string',
        kdbrg2: 'string',
        kdbrg3: 'string',
    }
}
